name: terraform lint

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  push:
    branches:
      - ci/**
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  terraform:
    name: Terraform Format & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Check Terraform Format
        run: terraform fmt -check --recursive

      - name: Terraform Validate
        run: terraform validate
